[package]
name = "mean_median_mode"
version = "0.1.0"
authors = ["Geoffrey Gane <geoffreygane@gmail.com>"]
edition = "2018"

[lib]
name = "compute"
path = "src/lib.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
